import json
import logging
from contextlib import asynccontextmanager
from typing import Optional

import jwt
from asyncpg import exceptions as pg_exceptions
from asyncpg import Pool, create_pool
from fastapi import HTTPException, Request

from app.exceptions import ServiceError
from config.config import (
    DB_HOST,
    DB_NAME,
    DB_PASSWORD,
    DB_PORT,
    DB_USER,
    MAX_POOL_SIZE,
)

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

db_pool: Optional[Pool] = None


async def _set_json_codecs(conn):
    await conn.set_type_codec(
        "jsonb",
        encoder=json.dumps,
        decoder=json.loads,
        schema="pg_catalog",
    )
    await conn.set_type_codec(
        "json",
        encoder=json.dumps,
        decoder=json.loads,
        schema="pg_catalog",
    )


async def _ensure_users_numeric_id(pool: Pool):
    """Add sequential numeric ID column for users if missing."""
    async with pool.acquire() as conn:
        try:
            await conn.execute(
                """
                ALTER TABLE aihr.users
                ADD COLUMN IF NOT EXISTS user_id BIGINT GENERATED BY DEFAULT AS IDENTITY
                """
            )
            await conn.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS idx_users_user_id
                ON aihr.users (user_id)
                """
            )
        except pg_exceptions.UndefinedTableError:
            log.warning("aihr.users table not found; skipped user_id numeric migration.")


async def close_db_pool():
    """Close the database connection pool."""
    if db_pool:
        await db_pool.close()
        log.info("Database connection pool closed successfully.")


async def init_db_pool():
    """Initialize the database connection pool."""
    global db_pool
    try:
        db_pool = await create_pool(
            user=DB_USER,
            password=DB_PASSWORD,
            host=DB_HOST,
            port=DB_PORT,
            database=DB_NAME,
            min_size=2,
            max_size=int(MAX_POOL_SIZE),
            max_inactive_connection_lifetime=300,
            command_timeout=30,
            server_settings={
                "timezone": "Asia/Almaty",
                "application_name": "my-alatau",
            },
            init=_set_json_codecs,
        )
        await _ensure_users_numeric_id(db_pool)
        log.info("Database connection pool initialized successfully.")
    except Exception as e:
        log.exception("Error initializing the database pool: %s", e)
        raise


@asynccontextmanager
async def get_db_connection():
    """
    Provides a database connection from the pool.
    Checks if the pool is initialized, otherwise raises an error.
    """
    if db_pool is None:
        raise ServiceError(status_id=0)  # TODO: set the required status_id
    async with db_pool.acquire() as conn:
        yield conn


@asynccontextmanager
async def get_db_connection_direct():
    """
    Gets a connection from db_pool using async with
    to guarantee proper connection release.
    """
    if db_pool is None:
        raise ServiceError(status_id=0)  # TODO: set the required status_id
    async with db_pool.acquire() as conn:
        yield conn


@asynccontextmanager
async def get_db_connection_as_admin():
    if db_pool is None:
        raise ServiceError(status_id=0)  # TODO: set the required status_id
    async with db_pool.acquire() as conn:
        await conn.execute("SET my.current_user_id = '1';")
        yield conn


@asynccontextmanager
async def get_db_connection_by_token(request: Request):
    if db_pool is None:
        raise ServiceError(status_id=0)  # TODO: set the required status_id

    auth_header = request.headers.get("Authorization")
    if not auth_header:
        raise HTTPException(status_code=401, detail="Missing Authorization header")
    try:
        scheme, token = auth_header.split()
        if scheme.lower() != "bearer":
            raise HTTPException(
                status_code=401, detail="Invalid authentication scheme"
            )
    except ValueError:
        raise HTTPException(
            status_code=401, detail="Invalid Authorization header format"
        )

    try:
        # Token decoding without signature verification.
        # Do not use this approach in production unless intentional.
        payload = jwt.decode(token, options={"verify_signature": False})
    except Exception:
        raise HTTPException(status_code=401, detail="Invalid token")

    user_id = payload.get("subject_id")
    if not user_id:
        raise HTTPException(status_code=401, detail="Token missing subject")

    async with db_pool.acquire() as conn:
        await conn.execute(f"SET my.current_user_id = '{user_id}';")
        yield conn, user_id


@asynccontextmanager
async def use_or_create_db(db=None):
    if db is None:
        log.info("Creating new database connection.")
        async with get_db_connection() as new_db:
            async with new_db.transaction():
                yield new_db
        return
    yield db


def get_db_conn(request: Request):
    """Extract connection from request.state set by middleware."""
    conn = getattr(request.state, "db", None)
    if conn is None:
        raise HTTPException(status_code=500, detail="DB connection not found")
    return conn
